/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MenuItem,
} from './interfaces/MenuItem';
import {
  WgFile,
} from './interfaces/WgFile';
import {
  EventEmitter,
} from '@stencil/core';
import {
  StyleCustomisation,
} from './interfaces/StyleCustomisation';
import {
  WizardStep,
} from './interfaces/Wizard';
import {
  Chapter,
} from './interfaces/Chapter';

export namespace Components {
  interface AppContainer {}
  interface AppMenu {
    'hamburgerMaxWidth'?: number;
    'itemRenderer'?: string;
    'menuItems'?: MenuItem[];
  }
  interface DropdownRenderer {
    'active': boolean;
    'somethingChanged': boolean;
    'url': any;
  }
  interface PskAppRouter {
    'failRedirectTo': string;
    'historyType': string;
    'menuItems'?: MenuItem[];
  }
  interface PskAttachmentsList {
    'files': WgFile[];
    'removeFileFromList'?: Function;
  }
  interface PskButton {
    'buttonClass': string;
    'disabled': boolean;
    'eventData': any;
    'eventEmitter': EventEmitter;
    'label': string;
  }
  interface PskCard {
    'id': string;
    'title': string;
  }
  interface PskChapter {
    'title': string;
  }
  interface PskDescription {
    'title': string;
  }
  interface PskExample {
    'title': string;
  }
  interface PskFilesChooser {
    'accept'?: string;
    'label': string;
    'onFilesChange'?: Function;
    'onFilesSelect'?: Function;
  }
  interface PskHoc {
    'title': string;
  }
  interface PskImg {
    'src': string;
    'title': string;
  }
  interface PskListFeedbacks {
    'alertRenderer': string;
    'messagesToDisplay': number;
    'styleCustomisation': StyleCustomisation;
    'timeAlive': number;
    'toastRenderer': string;
  }
  interface PskMenuItemRenderer {
    'active': boolean;
    'value': MenuItem;
  }
  interface PskModal {
    'opened': boolean;
  }
  interface PskPage {
    'tableOfContentTitle': string;
    'title': string;
  }
  interface PskPageLoader {
    'pageUrl': string;
  }
  interface PskPageNotFound {
    'basePath'?: string;
    'pageRenderer'?: string;
    'urlDestination'?: string;
  }
  interface PskPageNotFoundRenderer {}
  interface PskPinPopup {
    'opened': boolean;
  }
  interface PskStepper {
    'activeStep': WizardStep;
    'componentRender': string;
    'handleStepChange': Function;
    'wizardSteps': WizardStep[];
  }
  interface PskStepperRenderer {
    'activeStep': WizardStep;
    'handleStepChange': Function;
    'wizardSteps': WizardStep[];
  }
  interface PskTag {}
  interface PskToc {
    'chapterList': Array<Chapter>;
    'pageElement': HTMLElement;
    'title': string;
  }
  interface PskUiAlert {
    'message': any;
    'styleCustomisation': StyleCustomisation;
    'timeAlive': any;
    'typeOfAlert': string;
  }
  interface PskUiLoader {
    'shouldBeRendered': boolean;
  }
  interface PskUiToast {
    'message': any;
    'styleCustomisation': StyleCustomisation;
    'timeMeasure': string;
    'timeSinceCreation': number;
  }
  interface PskUserProfile {
    'profileRenderer': any;
    'userInfo': any;
  }
  interface PskUserProfileRenderer {
    'userInfo': any;
  }
  interface PskWizard {
    'componentRender': string;
    'wizardSteps'?: WizardStep[];
  }
}

declare global {


  interface HTMLAppContainerElement extends Components.AppContainer, HTMLStencilElement {}
  var HTMLAppContainerElement: {
    prototype: HTMLAppContainerElement;
    new (): HTMLAppContainerElement;
  };

  interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {}
  var HTMLAppMenuElement: {
    prototype: HTMLAppMenuElement;
    new (): HTMLAppMenuElement;
  };

  interface HTMLDropdownRendererElement extends Components.DropdownRenderer, HTMLStencilElement {}
  var HTMLDropdownRendererElement: {
    prototype: HTMLDropdownRendererElement;
    new (): HTMLDropdownRendererElement;
  };

  interface HTMLPskAppRouterElement extends Components.PskAppRouter, HTMLStencilElement {}
  var HTMLPskAppRouterElement: {
    prototype: HTMLPskAppRouterElement;
    new (): HTMLPskAppRouterElement;
  };

  interface HTMLPskAttachmentsListElement extends Components.PskAttachmentsList, HTMLStencilElement {}
  var HTMLPskAttachmentsListElement: {
    prototype: HTMLPskAttachmentsListElement;
    new (): HTMLPskAttachmentsListElement;
  };

  interface HTMLPskButtonElement extends Components.PskButton, HTMLStencilElement {}
  var HTMLPskButtonElement: {
    prototype: HTMLPskButtonElement;
    new (): HTMLPskButtonElement;
  };

  interface HTMLPskCardElement extends Components.PskCard, HTMLStencilElement {}
  var HTMLPskCardElement: {
    prototype: HTMLPskCardElement;
    new (): HTMLPskCardElement;
  };

  interface HTMLPskChapterElement extends Components.PskChapter, HTMLStencilElement {}
  var HTMLPskChapterElement: {
    prototype: HTMLPskChapterElement;
    new (): HTMLPskChapterElement;
  };

  interface HTMLPskDescriptionElement extends Components.PskDescription, HTMLStencilElement {}
  var HTMLPskDescriptionElement: {
    prototype: HTMLPskDescriptionElement;
    new (): HTMLPskDescriptionElement;
  };

  interface HTMLPskExampleElement extends Components.PskExample, HTMLStencilElement {}
  var HTMLPskExampleElement: {
    prototype: HTMLPskExampleElement;
    new (): HTMLPskExampleElement;
  };

  interface HTMLPskFilesChooserElement extends Components.PskFilesChooser, HTMLStencilElement {}
  var HTMLPskFilesChooserElement: {
    prototype: HTMLPskFilesChooserElement;
    new (): HTMLPskFilesChooserElement;
  };

  interface HTMLPskHocElement extends Components.PskHoc, HTMLStencilElement {}
  var HTMLPskHocElement: {
    prototype: HTMLPskHocElement;
    new (): HTMLPskHocElement;
  };

  interface HTMLPskImgElement extends Components.PskImg, HTMLStencilElement {}
  var HTMLPskImgElement: {
    prototype: HTMLPskImgElement;
    new (): HTMLPskImgElement;
  };

  interface HTMLPskListFeedbacksElement extends Components.PskListFeedbacks, HTMLStencilElement {}
  var HTMLPskListFeedbacksElement: {
    prototype: HTMLPskListFeedbacksElement;
    new (): HTMLPskListFeedbacksElement;
  };

  interface HTMLPskMenuItemRendererElement extends Components.PskMenuItemRenderer, HTMLStencilElement {}
  var HTMLPskMenuItemRendererElement: {
    prototype: HTMLPskMenuItemRendererElement;
    new (): HTMLPskMenuItemRendererElement;
  };

  interface HTMLPskModalElement extends Components.PskModal, HTMLStencilElement {}
  var HTMLPskModalElement: {
    prototype: HTMLPskModalElement;
    new (): HTMLPskModalElement;
  };

  interface HTMLPskPageElement extends Components.PskPage, HTMLStencilElement {}
  var HTMLPskPageElement: {
    prototype: HTMLPskPageElement;
    new (): HTMLPskPageElement;
  };

  interface HTMLPskPageLoaderElement extends Components.PskPageLoader, HTMLStencilElement {}
  var HTMLPskPageLoaderElement: {
    prototype: HTMLPskPageLoaderElement;
    new (): HTMLPskPageLoaderElement;
  };

  interface HTMLPskPageNotFoundElement extends Components.PskPageNotFound, HTMLStencilElement {}
  var HTMLPskPageNotFoundElement: {
    prototype: HTMLPskPageNotFoundElement;
    new (): HTMLPskPageNotFoundElement;
  };

  interface HTMLPskPageNotFoundRendererElement extends Components.PskPageNotFoundRenderer, HTMLStencilElement {}
  var HTMLPskPageNotFoundRendererElement: {
    prototype: HTMLPskPageNotFoundRendererElement;
    new (): HTMLPskPageNotFoundRendererElement;
  };

  interface HTMLPskPinPopupElement extends Components.PskPinPopup, HTMLStencilElement {}
  var HTMLPskPinPopupElement: {
    prototype: HTMLPskPinPopupElement;
    new (): HTMLPskPinPopupElement;
  };

  interface HTMLPskStepperElement extends Components.PskStepper, HTMLStencilElement {}
  var HTMLPskStepperElement: {
    prototype: HTMLPskStepperElement;
    new (): HTMLPskStepperElement;
  };

  interface HTMLPskStepperRendererElement extends Components.PskStepperRenderer, HTMLStencilElement {}
  var HTMLPskStepperRendererElement: {
    prototype: HTMLPskStepperRendererElement;
    new (): HTMLPskStepperRendererElement;
  };

  interface HTMLPskTagElement extends Components.PskTag, HTMLStencilElement {}
  var HTMLPskTagElement: {
    prototype: HTMLPskTagElement;
    new (): HTMLPskTagElement;
  };

  interface HTMLPskTocElement extends Components.PskToc, HTMLStencilElement {}
  var HTMLPskTocElement: {
    prototype: HTMLPskTocElement;
    new (): HTMLPskTocElement;
  };

  interface HTMLPskUiAlertElement extends Components.PskUiAlert, HTMLStencilElement {}
  var HTMLPskUiAlertElement: {
    prototype: HTMLPskUiAlertElement;
    new (): HTMLPskUiAlertElement;
  };

  interface HTMLPskUiLoaderElement extends Components.PskUiLoader, HTMLStencilElement {}
  var HTMLPskUiLoaderElement: {
    prototype: HTMLPskUiLoaderElement;
    new (): HTMLPskUiLoaderElement;
  };

  interface HTMLPskUiToastElement extends Components.PskUiToast, HTMLStencilElement {}
  var HTMLPskUiToastElement: {
    prototype: HTMLPskUiToastElement;
    new (): HTMLPskUiToastElement;
  };

  interface HTMLPskUserProfileElement extends Components.PskUserProfile, HTMLStencilElement {}
  var HTMLPskUserProfileElement: {
    prototype: HTMLPskUserProfileElement;
    new (): HTMLPskUserProfileElement;
  };

  interface HTMLPskUserProfileRendererElement extends Components.PskUserProfileRenderer, HTMLStencilElement {}
  var HTMLPskUserProfileRendererElement: {
    prototype: HTMLPskUserProfileRendererElement;
    new (): HTMLPskUserProfileRendererElement;
  };

  interface HTMLPskWizardElement extends Components.PskWizard, HTMLStencilElement {}
  var HTMLPskWizardElement: {
    prototype: HTMLPskWizardElement;
    new (): HTMLPskWizardElement;
  };
  interface HTMLElementTagNameMap {
    'app-container': HTMLAppContainerElement;
    'app-menu': HTMLAppMenuElement;
    'dropdown-renderer': HTMLDropdownRendererElement;
    'psk-app-router': HTMLPskAppRouterElement;
    'psk-attachments-list': HTMLPskAttachmentsListElement;
    'psk-button': HTMLPskButtonElement;
    'psk-card': HTMLPskCardElement;
    'psk-chapter': HTMLPskChapterElement;
    'psk-description': HTMLPskDescriptionElement;
    'psk-example': HTMLPskExampleElement;
    'psk-files-chooser': HTMLPskFilesChooserElement;
    'psk-hoc': HTMLPskHocElement;
    'psk-img': HTMLPskImgElement;
    'psk-list-feedbacks': HTMLPskListFeedbacksElement;
    'psk-menu-item-renderer': HTMLPskMenuItemRendererElement;
    'psk-modal': HTMLPskModalElement;
    'psk-page': HTMLPskPageElement;
    'psk-page-loader': HTMLPskPageLoaderElement;
    'psk-page-not-found': HTMLPskPageNotFoundElement;
    'psk-page-not-found-renderer': HTMLPskPageNotFoundRendererElement;
    'psk-pin-popup': HTMLPskPinPopupElement;
    'psk-stepper': HTMLPskStepperElement;
    'psk-stepper-renderer': HTMLPskStepperRendererElement;
    'psk-tag': HTMLPskTagElement;
    'psk-toc': HTMLPskTocElement;
    'psk-ui-alert': HTMLPskUiAlertElement;
    'psk-ui-loader': HTMLPskUiLoaderElement;
    'psk-ui-toast': HTMLPskUiToastElement;
    'psk-user-profile': HTMLPskUserProfileElement;
    'psk-user-profile-renderer': HTMLPskUserProfileRendererElement;
    'psk-wizard': HTMLPskWizardElement;
  }
}

declare namespace LocalJSX {
  interface AppContainer extends JSXBase.HTMLAttributes<HTMLAppContainerElement> {}
  interface AppMenu extends JSXBase.HTMLAttributes<HTMLAppMenuElement> {
    'hamburgerMaxWidth'?: number;
    'itemRenderer'?: string;
    'menuItems'?: MenuItem[];
    'onMenuEvent'?: (event: CustomEvent<any>) => void;
    'onNeedMenuItems'?: (event: CustomEvent<any>) => void;
  }
  interface DropdownRenderer extends JSXBase.HTMLAttributes<HTMLDropdownRendererElement> {
    'active'?: boolean;
    'somethingChanged'?: boolean;
    'url'?: any;
  }
  interface PskAppRouter extends JSXBase.HTMLAttributes<HTMLPskAppRouterElement> {
    'failRedirectTo'?: string;
    'historyType'?: string;
    'menuItems'?: MenuItem[];
    'onNeedMenuItems'?: (event: CustomEvent<any>) => void;
  }
  interface PskAttachmentsList extends JSXBase.HTMLAttributes<HTMLPskAttachmentsListElement> {
    'files'?: WgFile[];
    'removeFileFromList'?: Function;
  }
  interface PskButton extends JSXBase.HTMLAttributes<HTMLPskButtonElement> {
    'buttonClass'?: string;
    'disabled'?: boolean;
    'eventData'?: any;
    'eventEmitter'?: EventEmitter;
    'label'?: string;
  }
  interface PskCard extends JSXBase.HTMLAttributes<HTMLPskCardElement> {
    'id'?: string;
    'title'?: string;
  }
  interface PskChapter extends JSXBase.HTMLAttributes<HTMLPskChapterElement> {
    'onPsk-send-chapter'?: (event: CustomEvent<any>) => void;
    'title'?: string;
  }
  interface PskDescription extends JSXBase.HTMLAttributes<HTMLPskDescriptionElement> {
    'title'?: string;
  }
  interface PskExample extends JSXBase.HTMLAttributes<HTMLPskExampleElement> {
    'title'?: string;
  }
  interface PskFilesChooser extends JSXBase.HTMLAttributes<HTMLPskFilesChooserElement> {
    'accept'?: string;
    'label'?: string;
    'onFilesChange'?: Function;
    'onFilesSelect'?: Function;
  }
  interface PskHoc extends JSXBase.HTMLAttributes<HTMLPskHocElement> {
    'title'?: string;
  }
  interface PskImg extends JSXBase.HTMLAttributes<HTMLPskImgElement> {
    'src'?: string;
    'title'?: string;
  }
  interface PskListFeedbacks extends JSXBase.HTMLAttributes<HTMLPskListFeedbacksElement> {
    'alertRenderer'?: string;
    'messagesToDisplay'?: number;
    'onOpenFeedback'?: (event: CustomEvent<any>) => void;
    'styleCustomisation'?: StyleCustomisation;
    'timeAlive'?: number;
    'toastRenderer'?: string;
  }
  interface PskMenuItemRenderer extends JSXBase.HTMLAttributes<HTMLPskMenuItemRendererElement> {
    'active'?: boolean;
    'value'?: MenuItem;
  }
  interface PskModal extends JSXBase.HTMLAttributes<HTMLPskModalElement> {
    'onCloseModal'?: (event: CustomEvent<any>) => void;
    'opened'?: boolean;
  }
  interface PskPage extends JSXBase.HTMLAttributes<HTMLPskPageElement> {
    'tableOfContentTitle'?: string;
    'title'?: string;
  }
  interface PskPageLoader extends JSXBase.HTMLAttributes<HTMLPskPageLoaderElement> {
    'pageUrl'?: string;
  }
  interface PskPageNotFound extends JSXBase.HTMLAttributes<HTMLPskPageNotFoundElement> {
    'basePath'?: string;
    'pageRenderer'?: string;
    'urlDestination'?: string;
  }
  interface PskPageNotFoundRenderer extends JSXBase.HTMLAttributes<HTMLPskPageNotFoundRendererElement> {}
  interface PskPinPopup extends JSXBase.HTMLAttributes<HTMLPskPinPopupElement> {
    'onSendPin'?: (event: CustomEvent<any>) => void;
    'opened'?: boolean;
  }
  interface PskStepper extends JSXBase.HTMLAttributes<HTMLPskStepperElement> {
    'activeStep'?: WizardStep;
    'componentRender'?: string;
    'handleStepChange'?: Function;
    'wizardSteps'?: WizardStep[];
  }
  interface PskStepperRenderer extends JSXBase.HTMLAttributes<HTMLPskStepperRendererElement> {
    'activeStep'?: WizardStep;
    'handleStepChange'?: Function;
    'wizardSteps'?: WizardStep[];
  }
  interface PskTag extends JSXBase.HTMLAttributes<HTMLPskTagElement> {}
  interface PskToc extends JSXBase.HTMLAttributes<HTMLPskTocElement> {
    'chapterList'?: Array<Chapter>;
    'pageElement'?: HTMLElement;
    'title'?: string;
  }
  interface PskUiAlert extends JSXBase.HTMLAttributes<HTMLPskUiAlertElement> {
    'message'?: any;
    'onCloseFeedback'?: (event: CustomEvent<any>) => void;
    'styleCustomisation'?: StyleCustomisation;
    'timeAlive'?: any;
    'typeOfAlert'?: string;
  }
  interface PskUiLoader extends JSXBase.HTMLAttributes<HTMLPskUiLoaderElement> {
    'shouldBeRendered'?: boolean;
  }
  interface PskUiToast extends JSXBase.HTMLAttributes<HTMLPskUiToastElement> {
    'message'?: any;
    'onCloseFeedback'?: (event: CustomEvent<any>) => void;
    'styleCustomisation'?: StyleCustomisation;
    'timeMeasure'?: string;
    'timeSinceCreation'?: number;
  }
  interface PskUserProfile extends JSXBase.HTMLAttributes<HTMLPskUserProfileElement> {
    'onGetUserInfo'?: (event: CustomEvent<any>) => void;
    'profileRenderer'?: any;
    'userInfo'?: any;
  }
  interface PskUserProfileRenderer extends JSXBase.HTMLAttributes<HTMLPskUserProfileRendererElement> {
    'userInfo'?: any;
  }
  interface PskWizard extends JSXBase.HTMLAttributes<HTMLPskWizardElement> {
    'componentRender'?: string;
    'onChangeStep'?: (event: CustomEvent<any>) => void;
    'onFinishWizard'?: (event: CustomEvent<any>) => void;
    'onNeedWizardConfiguration'?: (event: CustomEvent<any>) => void;
    'wizardSteps'?: WizardStep[];
  }

  interface IntrinsicElements {
    'app-container': AppContainer;
    'app-menu': AppMenu;
    'dropdown-renderer': DropdownRenderer;
    'psk-app-router': PskAppRouter;
    'psk-attachments-list': PskAttachmentsList;
    'psk-button': PskButton;
    'psk-card': PskCard;
    'psk-chapter': PskChapter;
    'psk-description': PskDescription;
    'psk-example': PskExample;
    'psk-files-chooser': PskFilesChooser;
    'psk-hoc': PskHoc;
    'psk-img': PskImg;
    'psk-list-feedbacks': PskListFeedbacks;
    'psk-menu-item-renderer': PskMenuItemRenderer;
    'psk-modal': PskModal;
    'psk-page': PskPage;
    'psk-page-loader': PskPageLoader;
    'psk-page-not-found': PskPageNotFound;
    'psk-page-not-found-renderer': PskPageNotFoundRenderer;
    'psk-pin-popup': PskPinPopup;
    'psk-stepper': PskStepper;
    'psk-stepper-renderer': PskStepperRenderer;
    'psk-tag': PskTag;
    'psk-toc': PskToc;
    'psk-ui-alert': PskUiAlert;
    'psk-ui-loader': PskUiLoader;
    'psk-ui-toast': PskUiToast;
    'psk-user-profile': PskUserProfile;
    'psk-user-profile-renderer': PskUserProfileRenderer;
    'psk-wizard': PskWizard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


