/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppContainer {}
  interface AppMenu {
    'controller': any;
    'itemRenderer': string;
    'onMenuChanged'?: any;
  }
  interface AppMenuItem {}
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAppContainerElement extends Components.AppContainer, HTMLStencilElement {}
  var HTMLAppContainerElement: {
    prototype: HTMLAppContainerElement;
    new (): HTMLAppContainerElement;
  };

  interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {}
  var HTMLAppMenuElement: {
    prototype: HTMLAppMenuElement;
    new (): HTMLAppMenuElement;
  };

  interface HTMLAppMenuItemElement extends Components.AppMenuItem, HTMLStencilElement {}
  var HTMLAppMenuItemElement: {
    prototype: HTMLAppMenuItemElement;
    new (): HTMLAppMenuItemElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'app-container': HTMLAppContainerElement;
    'app-menu': HTMLAppMenuElement;
    'app-menu-item': HTMLAppMenuItemElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AppContainer extends JSXBase.HTMLAttributes<HTMLAppContainerElement> {}
  interface AppMenu extends JSXBase.HTMLAttributes<HTMLAppMenuElement> {
    'controller'?: any;
    'itemRenderer'?: string;
    'onMenuChanged'?: any;
    'onMenuEvent'?: (event: CustomEvent<any>) => void;
  }
  interface AppMenuItem extends JSXBase.HTMLAttributes<HTMLAppMenuItemElement> {}
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'app-container': AppContainer;
    'app-menu': AppMenu;
    'app-menu-item': AppMenuItem;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


